version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_2.0
    ports:
      - '9463:9463'
    volumes:
      - /App/Portfolio:/app
      - /app/node_modules
    restart: unless-stopped
