version: '3.8'

services:
  portfolio:
    image: fleeforezz/portfolio
    container_name: portfolio_2.0
    ports:
      - '9463:9463'
    volumes:
    - /home/nhat/portfolio
    restart: unless-stopped
