import { Work_Sans } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'

const workSans = Work_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Nhat Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico\"/>
      </head>
      <body className='bg-background'>
        <div id='stars-1'></div>
        <div id='stars-2'></div>
        <div id='stars-3'></div>
        <Header />
        {children}
        <video src="/blackhole.webm" autoPlay loop muted width={1250} height={1250} className="flex absolute -translate-x-96 -translate-y-80 -mt-8 -left-56 -z-50 rotate-180"></video>
        <Footer />
      </body>
    </html>
  );
}
