import Scroll from '@/components/SmoothScroll/SmoothScroll'
import './globals.css'

export const metadata = {
  title: 'Nhat | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='cursor-default'>
        {/* <Scroll /> */}
        {children}
      </body>
    </html>
  )
}
