# Persistent Volume
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: Portfolio
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 2000Mi

---
# Deployment Object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  selector:
    matchLabels:
      app: portfolio
  replicas: 2
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: fleeforezz/portfolio
        resources:
          limits:
            cpu: "1000m"
            memory: "1000Mi"
          request:
            cpu: "500m"
            memory: "750mi"
        ports:
        - containerPort: 9463
      automountServiceAccountToken: false

---
# Service Object
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  type: NodePort
  ports:
    - port: 9463
      targetPort: 9463
      nodePort: 32500